name: dotted_button
version: 0.0.1

description: |
  A new easy flutter package to have a custom button with various shape and dotted border.
topics: 
  - Custom Button
  - Dotted Border
  - Various Shape 
repository: https://github.com/bhusal-dip/Dotted-Button-Flutter

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
